{
 "title": "System",
 "tags": [
  "spring-boot",
  "actuator",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  }
 ]
}